/***************************************************************
 * Name:      mfp_wxwidgetsMain.h
 * Purpose:   Defines Application Frame
 * Author:    Aleksandar Krstic (aleksandar.krstic@d-logic.rs)
 * Created:   2019-02-20
 * Copyright: Aleksandar Krstic (www.d-logic.net)
 * License:
 **************************************************************/

#ifndef MFP_WXWIDGETSMAIN_H
#define MFP_WXWIDGETSMAIN_H

//(*Headers(mfp_wxwidgetsFrame)
#include <wx/button.h>
#include <wx/choice.h>
#include <wx/combobox.h>
#include <wx/frame.h>
#include <wx/menu.h>
#include <wx/notebook.h>
#include <wx/panel.h>
#include <wx/radiobut.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/statusbr.h>
#include <wx/textctrl.h>
#include <wx/timer.h>
//*)

class mfp_wxwidgetsFrame: public wxFrame
{
    public:

        mfp_wxwidgetsFrame(wxWindow* parent,wxWindowID id = -1);
        virtual ~mfp_wxwidgetsFrame();

    private:

        //(*Handlers(mfp_wxwidgetsFrame)
        void OnQuit(wxCommandEvent& event);
        void OnAbout(wxCommandEvent& event);
        void OnTimer1Trigger(wxTimerEvent& event);
        void OnbGetTypeAndUidClick(wxCommandEvent& event);
        void OnbPersonalizeCardClick(wxCommandEvent& event);
        void OnbAesAuthSL1Click(wxCommandEvent& event);
        void OnbAesAuthSL1Click1(wxCommandEvent& event);
        void OnbSwitchToSL3Click(wxCommandEvent& event);
        void OnButton3Click(wxCommandEvent& event);
        void OnButton4Click(wxCommandEvent& event);
        void OnButton5Click(wxCommandEvent& event);
        void OnbSetFieldConfigurationClick(wxCommandEvent& event);
        void OnbGetENCMACUidClick(wxCommandEvent& event);
        void OnbChangeVCPollingENCKeyClick(wxCommandEvent& event);
        void OnbChangeVCpolingMACKeyClick(wxCommandEvent& event);
        void OnbWriteCrypto1Click(wxCommandEvent& event);
        void OnbWriteAESClick(wxCommandEvent& event);
        void OnbUnlockKeysClick(wxCommandEvent& event);
        void OnbLockKeysClick(wxCommandEvent& event);
        void OnbBRProvidedKeyClick(wxCommandEvent& event);
        void OnbBRReaderKeyClick(wxCommandEvent& event);
        void OnbBRAKM1Click(wxCommandEvent& event);
        void OnbBRAKM2Click(wxCommandEvent& event);
        void OnbBSRProvidedKeyClick(wxCommandEvent& event);
        void OnbBSRReaderClick(wxCommandEvent& event);
        void OnbBSRAKM1Click(wxCommandEvent& event);
        void OnbBSRAKM2Click(wxCommandEvent& event);
        void OnbLRProvidedClick(wxCommandEvent& event);
        void OnbLRReaderClick(wxCommandEvent& event);
        void OnbLRAKM1Click(wxCommandEvent& event);
        void OnbLRAKM2Click(wxCommandEvent& event);
        void OnbBWProvidedKeyClick(wxCommandEvent& event);
        void OnbBWReaderKeyClick(wxCommandEvent& event);
        void OnbBWAKM1KeyClick(wxCommandEvent& event);
        void OnbBWAKM2KeyClick(wxCommandEvent& event);
        void OnbBSWProvidedKeyClick(wxCommandEvent& event);
        void OnbBSWReaderKeyClick(wxCommandEvent& event);
        void OnbBSWAKM1KeyClick(wxCommandEvent& event);
        void OnbBSWAKM2KeyClick(wxCommandEvent& event);
        void OnTimer2Trigger(wxTimerEvent& event);
        void OnbLWProvidedKeyClick(wxCommandEvent& event);
        void OnbLWReaderKeyClick(wxCommandEvent& event);
        void OnbLWAKM1KeyClick(wxCommandEvent& event);
        void OnbLWAKM2KeyClick(wxCommandEvent& event);
        void OnbChangeSectorKeysClick(wxCommandEvent& event);
        //*)

        //(*Identifiers(mfp_wxwidgetsFrame)
        static const long ID_STATICTEXT1;
        static const long ID_TEXTCTRL1;
        static const long ID_STATICTEXT2;
        static const long ID_TEXTCTRL2;
        static const long ID_RADIOBUTTON1;
        static const long ID_RADIOBUTTON2;
        static const long ID_STATICTEXT3;
        static const long ID_TEXTCTRL3;
        static const long ID_STATICTEXT4;
        static const long ID_TEXTCTRL4;
        static const long ID_STATICTEXT5;
        static const long ID_TEXTCTRL5;
        static const long ID_STATICTEXT6;
        static const long ID_TEXTCTRL6;
        static const long ID_STATICTEXT7;
        static const long ID_TEXTCTRL7;
        static const long ID_STATICTEXT8;
        static const long ID_TEXTCTRL8;
        static const long ID_STATICTEXT9;
        static const long ID_TEXTCTRL9;
        static const long ID_STATICTEXT10;
        static const long ID_TEXTCTRL10;
        static const long ID_STATICTEXT11;
        static const long ID_TEXTCTRL11;
        static const long ID_BUTTON1;
        static const long ID_STATICTEXT78;
        static const long ID_PANEL1;
        static const long ID_STATICTEXT14;
        static const long ID_TEXTCTRL13;
        static const long ID_STATICTEXT15;
        static const long ID_COMBOBOX1;
        static const long ID_BUTTON3;
        static const long ID_PANEL2;
        static const long ID_STATICTEXT16;
        static const long ID_TEXTCTRL14;
        static const long ID_STATICTEXT17;
        static const long ID_COMBOBOX2;
        static const long ID_BUTTON4;
        static const long ID_PANEL3;
        static const long ID_STATICTEXT18;
        static const long ID_TEXTCTRL15;
        static const long ID_STATICTEXT19;
        static const long ID_TEXTCTRL16;
        static const long ID_STATICTEXT20;
        static const long ID_COMBOBOX3;
        static const long ID_STATICTEXT21;
        static const long ID_TEXTCTRL17;
        static const long ID_BUTTON5;
        static const long ID_PANEL4;
        static const long ID_STATICTEXT22;
        static const long ID_TEXTCTRL18;
        static const long ID_STATICTEXT23;
        static const long ID_TEXTCTRL19;
        static const long ID_STATICTEXT24;
        static const long ID_COMBOBOX4;
        static const long ID_STATICTEXT25;
        static const long ID_TEXTCTRL20;
        static const long ID_BUTTON6;
        static const long ID_PANEL5;
        static const long ID_RADIOBUTTON3;
        static const long ID_RADIOBUTTON4;
        static const long ID_STATICTEXT26;
        static const long ID_COMBOBOX5;
        static const long ID_STATICTEXT108;
        static const long ID_STATICTEXT27;
        static const long ID_TEXTCTRL21;
        static const long ID_STATICTEXT28;
        static const long ID_TEXTCTRL22;
        static const long ID_STATICTEXT29;
        static const long ID_COMBOBOX6;
        static const long ID_STATICTEXT30;
        static const long ID_TEXTCTRL23;
        static const long ID_BUTTON7;
        static const long ID_PANEL6;
        static const long ID_RADIOBUTTON5;
        static const long ID_RADIOBUTTON6;
        static const long ID_STATICTEXT31;
        static const long ID_TEXTCTRL24;
        static const long ID_STATICTEXT32;
        static const long ID_COMBOBOX7;
        static const long ID_BUTTON8;
        static const long ID_PANEL7;
        static const long ID_STATICTEXT33;
        static const long ID_TEXTCTRL25;
        static const long ID_STATICTEXT34;
        static const long ID_TEXTCTRL26;
        static const long ID_STATICTEXT35;
        static const long ID_COMBOBOX8;
        static const long ID_STATICTEXT36;
        static const long ID_COMBOBOX9;
        static const long ID_BUTTON9;
        static const long ID_STATICTEXT45;
        static const long ID_TEXTCTRL33;
        static const long ID_PANEL8;
        static const long ID_STATICTEXT37;
        static const long ID_TEXTCTRL27;
        static const long ID_STATICTEXT38;
        static const long ID_TEXTCTRL28;
        static const long ID_STATICTEXT39;
        static const long ID_COMBOBOX10;
        static const long ID_STATICTEXT40;
        static const long ID_TEXTCTRL29;
        static const long ID_BUTTON10;
        static const long ID_PANEL9;
        static const long ID_STATICTEXT41;
        static const long ID_TEXTCTRL30;
        static const long ID_STATICTEXT42;
        static const long ID_TEXTCTRL31;
        static const long ID_STATICTEXT43;
        static const long ID_COMBOBOX11;
        static const long ID_STATICTEXT44;
        static const long ID_TEXTCTRL32;
        static const long ID_BUTTON11;
        static const long ID_PANEL10;
        static const long ID_RADIOBUTTON7;
        static const long ID_RADIOBUTTON8;
        static const long ID_STATICTEXT53;
        static const long ID_COMBOBOX14;
        static const long ID_STATICTEXT52;
        static const long ID_TEXTCTRL38;
        static const long ID_BUTTON16;
        static const long ID_RADIOBUTTON9;
        static const long ID_RADIOBUTTON10;
        static const long ID_STATICTEXT54;
        static const long ID_COMBOBOX15;
        static const long ID_STATICTEXT55;
        static const long ID_COMBOBOX16;
        static const long ID_STATICTEXT114;
        static const long ID_BUTTON17;
        static const long ID_RADIOBUTTON11;
        static const long ID_RADIOBUTTON12;
        static const long ID_STATICTEXT56;
        static const long ID_COMBOBOX17;
        static const long ID_BUTTON18;
        static const long ID_RADIOBUTTON13;
        static const long ID_RADIOBUTTON14;
        static const long ID_STATICTEXT57;
        static const long ID_COMBOBOX18;
        static const long ID_BUTTON19;
        static const long ID_STATICTEXT107;
        static const long ID_PANEL14;
        static const long ID_RADIOBUTTON15;
        static const long ID_RADIOBUTTON16;
        static const long ID_STATICTEXT68;
        static const long ID_COMBOBOX24;
        static const long ID_STATICTEXT58;
        static const long ID_COMBOBOX19;
        static const long ID_STATICTEXT59;
        static const long ID_TEXTCTRL39;
        static const long ID_BUTTON20;
        static const long ID_RADIOBUTTON17;
        static const long ID_RADIOBUTTON18;
        static const long ID_STATICTEXT71;
        static const long ID_COMBOBOX25;
        static const long ID_STATICTEXT60;
        static const long ID_COMBOBOX20;
        static const long ID_STATICTEXT61;
        static const long ID_COMBOBOX21;
        static const long ID_STATICTEXT113;
        static const long ID_BUTTON21;
        static const long ID_RADIOBUTTON19;
        static const long ID_RADIOBUTTON20;
        static const long ID_STATICTEXT74;
        static const long ID_COMBOBOX26;
        static const long ID_STATICTEXT62;
        static const long ID_COMBOBOX22;
        static const long ID_BUTTON22;
        static const long ID_RADIOBUTTON21;
        static const long ID_RADIOBUTTON22;
        static const long ID_STATICTEXT76;
        static const long ID_COMBOBOX27;
        static const long ID_STATICTEXT63;
        static const long ID_COMBOBOX23;
        static const long ID_BUTTON23;
        static const long ID_STATICTEXT106;
        static const long ID_PANEL15;
        static const long ID_RADIOBUTTON23;
        static const long ID_RADIOBUTTON24;
        static const long ID_STATICTEXT64;
        static const long ID_TEXTCTRL40;
        static const long ID_STATICTEXT69;
        static const long ID_TEXTCTRL41;
        static const long ID_STATICTEXT70;
        static const long ID_TEXTCTRL42;
        static const long ID_BUTTON24;
        static const long ID_RADIOBUTTON25;
        static const long ID_RADIOBUTTON26;
        static const long ID_STATICTEXT65;
        static const long ID_TEXTCTRL43;
        static const long ID_STATICTEXT72;
        static const long ID_TEXTCTRL44;
        static const long ID_STATICTEXT73;
        static const long ID_COMBOBOX28;
        static const long ID_STATICTEXT112;
        static const long ID_BUTTON25;
        static const long ID_RADIOBUTTON27;
        static const long ID_RADIOBUTTON28;
        static const long ID_STATICTEXT66;
        static const long ID_TEXTCTRL45;
        static const long ID_STATICTEXT75;
        static const long ID_TEXTCTRL46;
        static const long ID_BUTTON26;
        static const long ID_RADIOBUTTON29;
        static const long ID_RADIOBUTTON30;
        static const long ID_STATICTEXT67;
        static const long ID_TEXTCTRL47;
        static const long ID_STATICTEXT77;
        static const long ID_TEXTCTRL48;
        static const long ID_BUTTON27;
        static const long ID_STATICTEXT105;
        static const long ID_PANEL16;
        static const long ID_NOTEBOOK2;
        static const long ID_PANEL11;
        static const long ID_RADIOBUTTON31;
        static const long ID_RADIOBUTTON32;
        static const long ID_STATICTEXT80;
        static const long ID_COMBOBOX29;
        static const long ID_STATICTEXT81;
        static const long ID_TEXTCTRL50;
        static const long ID_BUTTON28;
        static const long ID_RADIOBUTTON33;
        static const long ID_RADIOBUTTON34;
        static const long ID_STATICTEXT82;
        static const long ID_COMBOBOX30;
        static const long ID_STATICTEXT83;
        static const long ID_COMBOBOX31;
        static const long ID_STATICTEXT111;
        static const long ID_BUTTON29;
        static const long ID_RADIOBUTTON35;
        static const long ID_RADIOBUTTON36;
        static const long ID_STATICTEXT84;
        static const long ID_COMBOBOX32;
        static const long ID_BUTTON30;
        static const long ID_RADIOBUTTON37;
        static const long ID_RADIOBUTTON38;
        static const long ID_STATICTEXT85;
        static const long ID_CHOICE1;
        static const long ID_BUTTON31;
        static const long ID_STATICTEXT103;
        static const long ID_PANEL17;
        static const long ID_RADIOBUTTON39;
        static const long ID_RADIOBUTTON40;
        static const long ID_STATICTEXT86;
        static const long ID_COMBOBOX33;
        static const long ID_STATICTEXT87;
        static const long ID_COMBOBOX34;
        static const long ID_STATICTEXT88;
        static const long ID_TEXTCTRL51;
        static const long ID_BUTTON32;
        static const long ID_RADIOBUTTON41;
        static const long ID_RADIOBUTTON42;
        static const long ID_STATICTEXT89;
        static const long ID_COMBOBOX35;
        static const long ID_STATICTEXT90;
        static const long ID_COMBOBOX36;
        static const long ID_STATICTEXT91;
        static const long ID_COMBOBOX37;
        static const long ID_STATICTEXT110;
        static const long ID_BUTTON33;
        static const long ID_RADIOBUTTON43;
        static const long ID_RADIOBUTTON44;
        static const long ID_STATICTEXT92;
        static const long ID_COMBOBOX38;
        static const long ID_STATICTEXT93;
        static const long ID_COMBOBOX39;
        static const long ID_BUTTON34;
        static const long ID_RADIOBUTTON45;
        static const long ID_RADIOBUTTON46;
        static const long ID_STATICTEXT94;
        static const long ID_COMBOBOX40;
        static const long ID_STATICTEXT95;
        static const long ID_COMBOBOX41;
        static const long ID_BUTTON35;
        static const long ID_STATICTEXT100;
        static const long ID_PANEL18;
        static const long ID_RADIOBUTTON47;
        static const long ID_RADIOBUTTON48;
        static const long ID_STATICTEXT96;
        static const long ID_TEXTCTRL52;
        static const long ID_STATICTEXT98;
        static const long ID_TEXTCTRL54;
        static const long ID_BUTTON2;
        static const long ID_RADIOBUTTON49;
        static const long ID_RADIOBUTTON50;
        static const long ID_STATICTEXT99;
        static const long ID_TEXTCTRL55;
        static const long ID_STATICTEXT101;
        static const long ID_COMBOBOX42;
        static const long ID_STATICTEXT109;
        static const long ID_BUTTON36;
        static const long ID_RADIOBUTTON51;
        static const long ID_RADIOBUTTON52;
        static const long ID_STATICTEXT102;
        static const long ID_TEXTCTRL57;
        static const long ID_BUTTON37;
        static const long ID_RADIOBUTTON53;
        static const long ID_RADIOBUTTON54;
        static const long ID_STATICTEXT104;
        static const long ID_TEXTCTRL59;
        static const long ID_BUTTON38;
        static const long ID_STATICTEXT97;
        static const long ID_PANEL19;
        static const long ID_NOTEBOOK3;
        static const long ID_STATICTEXT79;
        static const long ID_TEXTCTRL49;
        static const long ID_PANEL12;
        static const long ID_STATICTEXT46;
        static const long ID_TEXTCTRL34;
        static const long ID_STATICTEXT47;
        static const long ID_COMBOBOX12;
        static const long ID_BUTTON12;
        static const long ID_STATICTEXT48;
        static const long ID_TEXTCTRL35;
        static const long ID_STATICTEXT49;
        static const long ID_COMBOBOX13;
        static const long ID_BUTTON13;
        static const long ID_STATICTEXT50;
        static const long ID_TEXTCTRL36;
        static const long ID_BUTTON14;
        static const long ID_STATICTEXT51;
        static const long ID_TEXTCTRL37;
        static const long ID_BUTTON15;
        static const long ID_PANEL13;
        static const long ID_NOTEBOOK1;
        static const long ID_TEXTCTRL12;
        static const long ID_STATICTEXT12;
        static const long ID_STATICTEXT13;
        static const long idMenuQuit;
        static const long idMenuAbout;
        static const long ID_STATUSBAR1;
        static const long ID_TIMER1;
        static const long ID_TIMER2;
        //*)

        //(*Declarations(mfp_wxwidgetsFrame)
        wxButton* Button3;
        wxButton* Button4;
        wxButton* bAesAuthSL1;
        wxButton* bBRAKM1;
        wxButton* bBRAKM2;
        wxButton* bBRProvidedKey;
        wxButton* bBRReaderKey;
        wxButton* bBSRAKM1;
        wxButton* bBSRAKM2;
        wxButton* bBSRProvidedKey;
        wxButton* bBSRReader;
        wxButton* bBSWAKM1Key;
        wxButton* bBSWAKM2Key;
        wxButton* bBSWProvidedKey;
        wxButton* bBSWReaderKey;
        wxButton* bBWAKM1Key;
        wxButton* bBWAKM2Key;
        wxButton* bBWProvidedKey;
        wxButton* bBWReaderKey;
        wxButton* bChangeSectorKeys;
        wxButton* bChangeVCPollingENCKey;
        wxButton* bChangeVCpolingMACKey;
        wxButton* bGetENCMACUid;
        wxButton* bLRAKM1;
        wxButton* bLRAKM2;
        wxButton* bLRProvided;
        wxButton* bLRReader;
        wxButton* bLWAKM1Key;
        wxButton* bLWAKM2Key;
        wxButton* bLWProvidedKey;
        wxButton* bLWReaderKey;
        wxButton* bLockKeys;
        wxButton* bPersonalizeCard;
        wxButton* bSetFieldConfiguration;
        wxButton* bSwitchToSL3;
        wxButton* bUnlockKeys;
        wxButton* bWriteAES;
        wxButton* bWriteCrypto1;
        wxChoice* BW_AKM2_BlockNr;
        wxComboBox* AESKeyIndex;
        wxComboBox* AES_Index;
        wxComboBox* BR_AKM1_BlockNR;
        wxComboBox* BR_AKM2_BlockNR;
        wxComboBox* BR_BlockNr;
        wxComboBox* BR_Reader_BlockNr;
        wxComboBox* BR_Reader_KeyIndex;
        wxComboBox* BSR_AKM1_BlockNr;
        wxComboBox* BSR_AKM1_SectorNr;
        wxComboBox* BSR_AKM2_BlockNr;
        wxComboBox* BSR_AKM2_SectorNr;
        wxComboBox* BSR_BlockNr;
        wxComboBox* BSR_Reader_BlockNR;
        wxComboBox* BSR_Reader_KeyIndex;
        wxComboBox* BSR_Reader_SectorNr;
        wxComboBox* BSR_SectorNr;
        wxComboBox* BSW_AKM1_BlockNr;
        wxComboBox* BSW_AKM1_SectorNr;
        wxComboBox* BSW_AKM2_BlockNr;
        wxComboBox* BSW_AKM2_SectorNr;
        wxComboBox* BSW_Provided_BlockNr;
        wxComboBox* BSW_Provided_SectorNr;
        wxComboBox* BSW_Reader_BlockNr;
        wxComboBox* BSW_Reader_KeyIndex;
        wxComboBox* BSW_Reader_SectorNr;
        wxComboBox* BW_AKM1_BlockNr;
        wxComboBox* BW_Provided_BlockNr;
        wxComboBox* BW_Reader_BlockNr;
        wxComboBox* BW_Reader_KeyIndex;
        wxComboBox* ConfRK;
        wxComboBox* Crypto1Index;
        wxComboBox* CurrentConfIndex;
        wxComboBox* ENCKeyIndex;
        wxComboBox* FieldConfKeyIndex;
        wxComboBox* LR_ReaderKeyIndex;
        wxComboBox* LW_Reader_KeyIndex;
        wxComboBox* MACKeyIndex;
        wxComboBox* OldConfigIndex;
        wxComboBox* OldMasterIndex;
        wxComboBox* SL1RK;
        wxComboBox* SL3RK;
        wxComboBox* SectorNumber;
        wxNotebook* Notebook1;
        wxNotebook* Notebook2;
        wxNotebook* Notebook3;
        wxPanel* Panel10;
        wxPanel* Panel11;
        wxPanel* Panel12;
        wxPanel* Panel13;
        wxPanel* Panel14;
        wxPanel* Panel15;
        wxPanel* Panel16;
        wxPanel* Panel17;
        wxPanel* Panel18;
        wxPanel* Panel19;
        wxPanel* Panel1;
        wxPanel* Panel2;
        wxPanel* Panel3;
        wxPanel* Panel4;
        wxPanel* Panel5;
        wxPanel* Panel6;
        wxPanel* Panel7;
        wxPanel* Panel8;
        wxPanel* Panel9;
        wxRadioButton* BR_AKM1_KeyA;
        wxRadioButton* BR_AKM1_KeyB;
        wxRadioButton* BR_AKM2_KeyA;
        wxRadioButton* BR_AKM2_KeyB;
        wxRadioButton* BR_Provided_A;
        wxRadioButton* BR_Provided_B;
        wxRadioButton* BR_Reader_KeyA;
        wxRadioButton* BR_Reader_KeyB;
        wxRadioButton* BSR_AKM1_KeyA;
        wxRadioButton* BSR_AKM1_KeyB;
        wxRadioButton* BSR_AKM2_KeyA;
        wxRadioButton* BSR_AKM2_KeyB;
        wxRadioButton* BSR_Provided_KeyA;
        wxRadioButton* BSR_Provided_KeyB;
        wxRadioButton* BSR_Reader_KeyA;
        wxRadioButton* BSR_Reader_KeyB;
        wxRadioButton* BSW_AKM1_KeyA;
        wxRadioButton* BSW_AKM1_KeyB;
        wxRadioButton* BSW_AKM2_KeyA;
        wxRadioButton* BSW_AKM2_KeyB;
        wxRadioButton* BSW_Provided_KeyA;
        wxRadioButton* BSW_Provided_KeyB;
        wxRadioButton* BSW_Reader_KeyA;
        wxRadioButton* BSW_Reader_KeyB;
        wxRadioButton* BW_AKM1_KeyA;
        wxRadioButton* BW_AKM1_KeyB;
        wxRadioButton* BW_AKM2_KeyA;
        wxRadioButton* BW_AKM2_KeyB;
        wxRadioButton* BW_Provided_KeyA;
        wxRadioButton* BW_Provided_KeyB;
        wxRadioButton* BW_Reader_KeyA;
        wxRadioButton* BW_Reader_KeyB;
        wxRadioButton* LR_AKM1_KeyA;
        wxRadioButton* LR_AKM1_KeyB;
        wxRadioButton* LR_AKM2_KeyA;
        wxRadioButton* LR_AKM2_KeyB;
        wxRadioButton* LR_Provided_KeyA;
        wxRadioButton* LR_Provided_KeyB;
        wxRadioButton* LR_Reader_KeyA;
        wxRadioButton* LR_Reader_KeyB;
        wxRadioButton* LW_AKM1_KeyA;
        wxRadioButton* LW_AKM1_KeyB;
        wxRadioButton* LW_AKM2_KeyA;
        wxRadioButton* LW_AKM2_KeyB;
        wxRadioButton* LW_Provided_KeyA;
        wxRadioButton* LW_Provided_KeyB;
        wxRadioButton* LW_Reader_KeyA;
        wxRadioButton* LW_Reader_KeyB;
        wxRadioButton* RBProvided;
        wxRadioButton* RBReader;
        wxRadioButton* RB_AES_KEY_A;
        wxRadioButton* RB_AES_KEY_B;
        wxRadioButton* RB_UseRandomID;
        wxRadioButton* RB_UseUID;
        wxStaticText* StaticText100;
        wxStaticText* StaticText101;
        wxStaticText* StaticText102;
        wxStaticText* StaticText103;
        wxStaticText* StaticText104;
        wxStaticText* StaticText105;
        wxStaticText* StaticText106;
        wxStaticText* StaticText107;
        wxStaticText* StaticText108;
        wxStaticText* StaticText109;
        wxStaticText* StaticText10;
        wxStaticText* StaticText110;
        wxStaticText* StaticText111;
        wxStaticText* StaticText112;
        wxStaticText* StaticText113;
        wxStaticText* StaticText11;
        wxStaticText* StaticText12;
        wxStaticText* StaticText13;
        wxStaticText* StaticText14;
        wxStaticText* StaticText15;
        wxStaticText* StaticText16;
        wxStaticText* StaticText17;
        wxStaticText* StaticText18;
        wxStaticText* StaticText19;
        wxStaticText* StaticText1;
        wxStaticText* StaticText20;
        wxStaticText* StaticText21;
        wxStaticText* StaticText22;
        wxStaticText* StaticText23;
        wxStaticText* StaticText24;
        wxStaticText* StaticText25;
        wxStaticText* StaticText26;
        wxStaticText* StaticText27;
        wxStaticText* StaticText28;
        wxStaticText* StaticText29;
        wxStaticText* StaticText2;
        wxStaticText* StaticText30;
        wxStaticText* StaticText31;
        wxStaticText* StaticText32;
        wxStaticText* StaticText33;
        wxStaticText* StaticText34;
        wxStaticText* StaticText35;
        wxStaticText* StaticText36;
        wxStaticText* StaticText37;
        wxStaticText* StaticText38;
        wxStaticText* StaticText39;
        wxStaticText* StaticText3;
        wxStaticText* StaticText40;
        wxStaticText* StaticText41;
        wxStaticText* StaticText42;
        wxStaticText* StaticText43;
        wxStaticText* StaticText44;
        wxStaticText* StaticText45;
        wxStaticText* StaticText46;
        wxStaticText* StaticText47;
        wxStaticText* StaticText48;
        wxStaticText* StaticText49;
        wxStaticText* StaticText4;
        wxStaticText* StaticText50;
        wxStaticText* StaticText51;
        wxStaticText* StaticText52;
        wxStaticText* StaticText53;
        wxStaticText* StaticText54;
        wxStaticText* StaticText55;
        wxStaticText* StaticText56;
        wxStaticText* StaticText57;
        wxStaticText* StaticText58;
        wxStaticText* StaticText59;
        wxStaticText* StaticText5;
        wxStaticText* StaticText60;
        wxStaticText* StaticText61;
        wxStaticText* StaticText62;
        wxStaticText* StaticText63;
        wxStaticText* StaticText64;
        wxStaticText* StaticText65;
        wxStaticText* StaticText66;
        wxStaticText* StaticText67;
        wxStaticText* StaticText68;
        wxStaticText* StaticText69;
        wxStaticText* StaticText6;
        wxStaticText* StaticText70;
        wxStaticText* StaticText71;
        wxStaticText* StaticText72;
        wxStaticText* StaticText73;
        wxStaticText* StaticText74;
        wxStaticText* StaticText75;
        wxStaticText* StaticText76;
        wxStaticText* StaticText77;
        wxStaticText* StaticText78;
        wxStaticText* StaticText79;
        wxStaticText* StaticText7;
        wxStaticText* StaticText80;
        wxStaticText* StaticText81;
        wxStaticText* StaticText82;
        wxStaticText* StaticText83;
        wxStaticText* StaticText84;
        wxStaticText* StaticText85;
        wxStaticText* StaticText86;
        wxStaticText* StaticText87;
        wxStaticText* StaticText88;
        wxStaticText* StaticText89;
        wxStaticText* StaticText8;
        wxStaticText* StaticText90;
        wxStaticText* StaticText91;
        wxStaticText* StaticText92;
        wxStaticText* StaticText93;
        wxStaticText* StaticText94;
        wxStaticText* StaticText95;
        wxStaticText* StaticText96;
        wxStaticText* StaticText97;
        wxStaticText* StaticText98;
        wxStaticText* StaticText99;
        wxStaticText* StaticText9;
        wxStaticText* StatusLabel;
        wxStatusBar* StatusBar1;
        wxTextCtrl* AES_TB;
        wxTextCtrl* BR_Key;
        wxTextCtrl* BSR_Key;
        wxTextCtrl* BSW_Provided_Key;
        wxTextCtrl* BW_Provided_Key;
        wxTextCtrl* CType;
        wxTextCtrl* CUid;
        wxTextCtrl* CardConfKeyTB;
        wxTextCtrl* CardConfigurationKeyTB;
        wxTextCtrl* CardMasterKeyTB;
        wxTextCtrl* Crypto1TB;
        wxTextCtrl* CurrentConfKeyTB;
        wxTextCtrl* ENCKeyTB;
        wxTextCtrl* ENCMACUidTB;
        wxTextCtrl* FieldConfKeyTB;
        wxTextCtrl* LR_AKM1_Addr;
        wxTextCtrl* LR_AKM1_Bytes;
        wxTextCtrl* LR_AKM2_Addr;
        wxTextCtrl* LR_AKM2_Bytes;
        wxTextCtrl* LR_Key;
        wxTextCtrl* LR_ProvidedAddr;
        wxTextCtrl* LR_Provided_Bytes;
        wxTextCtrl* LR_ReaderAddr;
        wxTextCtrl* LR_ReaderBytes;
        wxTextCtrl* LW_AKM1_Addr;
        wxTextCtrl* LW_AKM2_Addr;
        wxTextCtrl* LW_Provided_Addr;
        wxTextCtrl* LW_Provided_Key;
        wxTextCtrl* LW_Reader_Addr;
        wxTextCtrl* Level2SwitchKeyTB;
        wxTextCtrl* Level3SwitchKeyTB;
        wxTextCtrl* LockKeysTB;
        wxTextCtrl* MACKeyTB;
        wxTextCtrl* NewAesSectorKeyRK;
        wxTextCtrl* NewAesSectorKeyTB;
        wxTextCtrl* NewConfigKeyRK;
        wxTextCtrl* NewConfigKeyTB;
        wxTextCtrl* NewMACTB;
        wxTextCtrl* NewMACTB_RK;
        wxTextCtrl* NewMasterRK;
        wxTextCtrl* NewMasterTB;
        wxTextCtrl* NewVCPollingENCKeyRK;
        wxTextCtrl* NewVCPollingENCKeyTB;
        wxTextCtrl* OldAesSectorKeyTB;
        wxTextCtrl* OldConfigKeyTB;
        wxTextCtrl* OldMasterTB;
        wxTextCtrl* ProximityCheckKeyTB;
        wxTextCtrl* ReaderInfo;
        wxTextCtrl* SL1AuthKeyTB;
        wxTextCtrl* SL1CardAuthKeyTB;
        wxTextCtrl* SelectVCKeyTB;
        wxTextCtrl* SwitchSL3KeyTB;
        wxTextCtrl* UnlockKeysTB;
        wxTextCtrl* VCPollingEncKeyTB;
        wxTextCtrl* VCPollingMacKeyTB;
        wxTextCtrl* WriteDataTB;
        wxTimer Timer1;
        wxTimer Timer2;
        //*)

        DECLARE_EVENT_TABLE()
};

#endif // MFP_WXWIDGETSMAIN_H
